# Generated by Django 4.1.7 on 2023-03-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todoitem_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
